FROM python:3

RUN mkdir -p /usr/src/bot

WORKDIR /usr/src/bot
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get -y install ffmpeg


COPY . .

CMD [ "python3", "manaschi.py", "prod"]
