# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: mankurt
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
#      ME: "***REMOVED***"
#      DISCORD_TOKEN: "***REMOVED***"
      TEST_USER_TOKEN: "***REMOVED***"
#      DISCORD_GUILD: "***REMOVED***"
#      SENECA_API_TOKEN: "***REMOVED***"
#      DB_USER: "***REMOVED***"
#      DB_PASSWORD: "***REMOVED***"
#      DB_HOST: "***REMOVED***"
#      DB_DATABASE: "***REMOVED***"    
#      QUOTES_KEY: ${{ secrets.QUOTES_KEY }}
#      FOOD_KEY: ${{ secrets.FOOD_KEY }}
#      MANASCHI: "***REMOVED***"
#      TEST_DB_DATABASE: "***REMOVED***"
#      TEST_DISCORD_GUILD: "***REMOVED***"
      TEST_CHANNEL: "***REMOVED***"
      TEST_TARGET: "***REMOVED***"
#      TEST_USER: "***REMOVED***"
    strategy:
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Retrieving keystore
        run: |
          echo "$KEYSTORE_BASE64"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 --decode > my_production.keystore

      - name: Running the Tester Bot
        run: | 
          docker stop zanshin_discord_bot || true
          docker container prune --force
          docker build -t zanshin --file Dockerfile_Test .
          cat my_production.keystore
          docker run --env-file my_production.keystore -d --name zanshin_discord_bot zanshin
#          docker run --env DISCORD_TOKEN=$DISCORD_TOKEN --env ME=$ME --env DISCORD_GUILD=$DISCORD_GUILD --env SENECA_API_TOKEN=$SENECA_API_TOKEN --env DB_USER=$DB_USER --env DB_PASSWORD=$DB_PASSWORD --env DB_HOST=$DB_HOST --env DB_DATABASE=$DB_DATABASE --env QUOTES_KEY=$QUOTES_KEY --env FOOD_KEY=$FOOD_KEY --env MANASCHI=$MANASCHI --env TEST_DB_DATABASE=$TEST_DB_DATABASE --env TEST_DISCORD_GUILD=$TEST_DISCORD_GUILD --env TEST_CHANNEL=$TEST_CHANNEL --env TEST_TARGET=$TEST_TARGET --env TEST_USER=$TEST_USER -d --name zanshin_discord_bot zanshin 

      - name: Running Tests
        run: |
          docker stop zanshin_runner || true
          docker container prune --force
          docker build -t zanshin_runner --file Dockerfile_Tester .
          docker run --env-file my_production.keystore --name zanshin_runner zanshin_runner       
#          python3 example_tester.py -c $TEST_CHANNEL --run all $TEST_TARGET $TEST_USER_TOKEN

      - name: Stopping the Tester Bot and the Runner container
        run: |
          docker stop zanshin_discord_bot || true
          docker stop zanshin_runner || true
          
      # Runs a single command using the runners shell
      - name: Running The Bot
        run: | 
          docker build -t mankurt .
          docker stop mankurt_discord_bot
          docker container prune --force
          docker run --env-file my_production.keystore -d --name mankurt_discord_bot mankurt 
#          docker run --env DISCORD_TOKEN=$DISCORD_TOKEN --env ME=$ME --env DISCORD_GUILD=$DISCORD_GUILD --env SENECA_API_TOKEN=$SENECA_API_TOKEN --env DB_USER=$DB_USER --env DB_PASSWORD=$DB_PASSWORD --env DB_HOST=$DB_HOST --env DB_DATABASE=$DB_DATABASE --env QUOTES_KEY=$QUOTES_KEY --env FOOD_KEY=$FOOD_KEY --env MANASCHI=$MANASCHI --env TEST_DB_DATABASE=$TEST_DB_DATABASE --env TEST_DISCORD_GUILD=$TEST_DISCORD_GUILD --env TEST_CHANNEL=$TEST_CHANNEL --env TEST_TARGET=$TEST_TARGET --env TEST_USER=$TEST_USER -d --name mankurt_discord_bot mankurt 
          
