# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: mankurt
    env:
      ME: ${{ secrets.ME }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
      SENECA_API_TOKEN: ${{ secrets.SENECA_API_TOKEN }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      QUOTES_KEY: ${{ secrets.QUOTES_KEY }}
      FOOD_KEY: ${{ secrets.FOOD_KEY }}
      MANASCHI: ${{ secrets.MANASCHI }}
    strategy:
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip3 install -r requirements.txt
          
      # Runs a single command using the runners shell
      - name: Running The Bot
        run: | 
          docker build -t mankurt .
          docker run mankurt -e ME=${{ secrets.ME }} \
                             -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
                             -e DISCORD_GUILD=${{ secrets.DISCORD_GUILD }} \
                             -e SENECA_API_TOKEN=${{ secrets.SENECA_API_TOKEN }} \
                             -e DB_USER=${{ secrets.DB_USER }} \
                             -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                             -e DB_HOST=${{ secrets.DB_HOST }} \
                             -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
                             -e QUOTES_KEY=${{ secrets.QUOTES_KEY }} \ 
                             -e FOOD_KEY=${{ secrets.FOOD_KEY }} \
                             -e MANASCHI=${{ secrets.MANASCHI }} \
          
